{% set name = "djangorestframework-gis" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djangorestframework_gis-{{ version }}.tar.gz
  sha256: 702ba9ad44173b7cc70e48c6c84da48c28f6f82612cc901a77fdb54c5c57c971

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - django >=4.2
    - python >={{ python_min }}
    - djangorestframework >=3.12,<3.17
    - django-filter >=23.5,<26.0

test:
  imports:
    - rest_framework_gis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/djangonauts/django-rest-framework-gis
  summary: Geographic add-ons for Django Rest Framework
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/djangonauts/django-rest-framework-gis
  dev_url: https://github.com/djangonauts/django-rest-framework-gis

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
